In [1]:
## ライブラリのインポート ##
import os
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt


In [2]:

## テキストデータをnumpy形式に変換する(解析のための下準備) ##
###  必ず使用する  ###
def Text2Numpy(**args):
    """
    大学にある重心動揺計の計測データ（csv）を取り込み，pythonで処理しやすいように変換するための関数
    filename:処理したいファイル名
    """    
    ## データを開く ##
    with open(args["filename"],"r",encoding="shift-jis") as dat:
        datacop= dat.read()

    ## 書き出し先を作る ##
    COPdata = {"ID":None,"sex":None,"age":None,"height":None,"weight":None,"cop":[]}
    attribute = {"ID":0,"sex":2,"age":3,"height":4,"weight":5}
    ## 処理1 ##
    ### データの整理 ###
    d0 = datacop.split("\n") # スプリット
    COPdata["ID"] = d0[attribute["ID"]].split(",")[1][1:-1]# IDの取り出し
    COPdata["sex"] = d0[attribute["sex"]].split(",")[1][1:-1]# 性別の取り出し
    COPdata["age"] = (d0[attribute["age"]].split(",")[1][1:-1])# 年齢の取り出し
    COPdata["height"] = (d0[attribute["height"]].split(",")[1][1:-1])# 身長の取り出し
    COPdata["weight"] = (d0[attribute["weight"]].split(",")[1][1:-1])# 体重の取り出し

    for i in d0[7:]:
        if len(i)==0:
            break
            
        nn = i.split(",")
        if args["Weightshow"]==True:
            ww = nn[0:3]+[nn[5]]
        else:
            ww = nn[0:3]
            
        COPdata["cop"].append(list(map(float,ww)))

    COPdata["cop"] = np.array(COPdata["cop"])
    
    ## 処理1完了 ##
    return COPdata

In [5]:
A = Text2Numpy(filename="/Users/tumh/Desktop/181P222_1.csv",Weightshow=False)

In [6]:
A.keys()

dict_keys(['ID', 'sex', 'age', 'height', 'weight', 'cop'])

In [26]:
B = A["cop"]

In [29]:
B[2]-B[0]

array([0.02, 0.  , 0.  ])

In [8]:
with open("/Users/tumh/Desktop/181P222_1.csv","r",encoding="shift-jis") as dat:
    datacop= dat.read()

In [14]:
datacop

'"ID番号","181P222","眼","開眼"\n"氏名","takarazuka","姿勢","立位"\n"性別","男","病名","正常"\n"年齢","19.00","メモ",\n"身長(cm)","175.50","検査者",\n"体重(kg)","20.00"\n"時間(秒)","総合COP左右X(cm)","総合COP前後Y(cm)","左プレートCOP左右X(cm)","左プレートCOP前後Y(cm)","左荷重(kgf)","右プレートCOP左右X(cm)","右プレートCOP前後Y(cm)","右荷重(kgf)","","","",""\n0.000,-1.277,-1.538,"---.---","---.---",10.028,"---.---","---.---","---.---","","","",""\n0.010,-1.290,-1.532,"---.---","---.---",10.024,"---.---","---.---","---.---","","","",""\n0.020,-1.277,-1.538,"---.---","---.---",10.028,"---.---","---.---","---.---","","","",""\n0.030,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""\n0.040,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""\n0.050,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""\n0.060,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""\n0.070,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","

In [15]:
d0 = datacop.split("\n") 

In [16]:
d0

['"ID番号","181P222","眼","開眼"',
 '"氏名","takarazuka","姿勢","立位"',
 '"性別","男","病名","正常"',
 '"年齢","19.00","メモ",',
 '"身長(cm)","175.50","検査者",',
 '"体重(kg)","20.00"',
 '"時間(秒)","総合COP左右X(cm)","総合COP前後Y(cm)","左プレートCOP左右X(cm)","左プレートCOP前後Y(cm)","左荷重(kgf)","右プレートCOP左右X(cm)","右プレートCOP前後Y(cm)","右荷重(kgf)","","","",""',
 '0.000,-1.277,-1.538,"---.---","---.---",10.028,"---.---","---.---","---.---","","","",""',
 '0.010,-1.290,-1.532,"---.---","---.---",10.024,"---.---","---.---","---.---","","","",""',
 '0.020,-1.277,-1.538,"---.---","---.---",10.028,"---.---","---.---","---.---","","","",""',
 '0.030,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""',
 '0.040,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""',
 '0.050,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""',
 '0.060,-1.265,-1.544,"---.---","---.---",10.033,"---.---","---.---","---.---","","","",""',
 '0.070,-1.265,-1.544,"---.---","---.---",1

In [19]:
a = ""

In [20]:
str(a)

''

In [23]:
len(d0[-2])

89

In [30]:
import pandas as pd

In [33]:
dat = pd.read_csv("/Users/tumh/Desktop/181P222_1.csv",names=["a","b"])

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 2: invalid start byte

In [34]:
os.chdir("/Users/tumh/Desktop/test")

In [38]:
filename = os.listdir()
filename

['181P009_1.csv',
 '181P009_2.csv',
 '181P048_2.csv',
 '181P048_1.csv',
 '181P076_2.csv',
 '181P015_1.csv',
 '181P111_1.csv',
 '181P015_2.csv',
 '181P076_1.csv',
 '181P111_2.csv',
 '181P039_1.csv',
 '181P041_1.csv',
 '181P039_2.csv',
 '181P041_2.csv',
 '181P222_2.csv',
 '181P222_1.csv',
 '181P021_2.csv',
 '181P021_1.csv']

In [43]:
for i in filename:
    SS =Text2Numpy(filename=i,Weightshow=False)
    print(SS["cop"][0])

[ 0.     0.303 -6.709]
[ 0.    -0.162 -5.439]
[ 0.     0.375 -2.559]
[ 0.    -0.501 -1.797]
[ 0.    -0.037 -0.35 ]
[ 0.     0.408 -2.148]
[ 0.    -4.929  0.344]
[ 0.     1.158 -2.501]
[ 0.    -0.216  0.351]
[ 0.    -0.728 -1.008]
[ 0.    -0.081 -1.585]
[ 0.    -0.883 -4.154]
[ 0.    -0.397 -1.351]
[ 0.    -0.046 -4.199]
[ 0.    -1.299 -1.563]
[ 0.    -1.277 -1.538]
[ 0.     0.261 -3.989]
[ 0.    -1.05  -2.495]
